name       : sway
version    : 1.8.1
release    : 26
source     :
    - https://github.com/swaywm/sway/archive/refs/tags/1.8.1.tar.gz : e9f575761342fc8fe0cfeea80c90f32ddfa8c543572fec179f40922346f47dff
license    : MIT
homepage   : https://swaywm.org/
component  : desktop
summary    : sway is an i3-compatible Wayland compositor
description: |
    sway is an i3-compatible Wayland compositor.
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(cairo)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(json-c)
    - pkgconfig(libavcodec)
    - pkgconfig(libevdev)
    - pkgconfig(libcap)
    - pkgconfig(pango)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wlroots)
rundeps    :
    - alacritty
    - dmenu
    - swaybg
    - swayidle
    - swaylock
setup      : |
    %patch -p1 < $pkgfiles/0001-Make-sway-stateless.patch
    %patch -p1 < $pkgfiles/0002-Better-OOTB-default-config.patch
    %meson_configure -Dgdk-pixbuf=enabled -Dxwayland=enabled -Ddefault_sysconfdir=/usr/share/defaults
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 $pkgfiles/sway.desktop $installdir/usr/share/xsessions/sway.desktop
