name       : sway
version    : '1.4'
release    : 16
source     :
    - https://github.com/swaywm/sway/releases/download/1.4/sway-1.4.tar.gz : e2805291fc01d49e21dda4b273e38170d1fff4e1757215439729edbed880dfbe
license    : MIT
component  : desktop
summary    : sway is an i3-compatible Wayland compositor
description: |
    sway is an i3-compatible Wayland compositor
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(cairo)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(json-c)
    - pkgconfig(libavcodec)
    - pkgconfig(libevdev)
    - pkgconfig(libcap)
    - pkgconfig(pango)
    - pkgconfig(wlc)
    - pkgconfig(wlroots)
rundeps    :
    - swaylock
setup      : |
    %meson_configure -Dgdk-pixbuf=enabled -Dxwayland=enabled
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 $pkgfiles/sway.desktop $installdir/usr/share/xsessions/sway.desktop
