name       : sway
version    : 0.11
release    : 2
source     :
    - https://github.com/SirCmpwn/sway/archive/0.11.tar.gz : 3d4d18afc849db8704d8da9cb69eb121ea92b27d7fa556acdcc6708f05c84964
license    : MIT
component  : desktop
summary    : sway is an i3-compatible Wayland compositor
description: |
    sway is an i3-compatible Wayland compositor
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(cairo)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(json-c)
    - pkgconfig(libavcodec)
    - pkgconfig(libcap)
    - pkgconfig(pango)
    - pkgconfig(wlc)
    - asciidoc
setup      : |
    %cmake -Dzsh-completions=ON .
build      : |
    %make
install    : "%make_install  \n"
