name       : sway
version    : 0.14.0
release    : 7
source     :
    - https://github.com/SirCmpwn/sway/archive/0.14.0.tar.gz : e63efee81cd3952ee00c7bd379cf90b065530b03423f593895584aa51e9c7f1b
license    : MIT
component  : desktop
summary    : sway is an i3-compatible Wayland compositor
description: |
    sway is an i3-compatible Wayland compositor
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(cairo)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(json-c)
    - pkgconfig(libavcodec)
    - pkgconfig(libcap)
    - pkgconfig(pango)
    - pkgconfig(wlc)
    - asciidoc
setup      : |
    %cmake -DVERSION=0.14.0 -Dzsh-completions=ON .
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/sway.desktop $installdir/usr/share/xsessions/sway.desktop