name       : sway
version    : 0.15.1
release    : 8
source     :
    - https://github.com/swaywm/sway/archive/0.15.1.tar.gz : b4305581587b1072f5cb61387230aaf731ea9ea0d01fdf198856a757e2195149
license    : MIT
component  : desktop
summary    : sway is an i3-compatible Wayland compositor
description: |
    sway is an i3-compatible Wayland compositor
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(cairo)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(json-c)
    - pkgconfig(libavcodec)
    - pkgconfig(libcap)
    - pkgconfig(pango)
    - pkgconfig(wlc)
    - asciidoc
setup      : |
    %cmake -DVERSION=${version} -Dzsh-completions=ON .
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/sway.desktop $installdir/usr/share/xsessions/sway.desktop
