name       : sway
version    : '1.6'
release    : 20
source     :
    - https://github.com/swaywm/sway/releases/download/1.6/sway-1.6.tar.gz : 9ecfd2f38239f7e90922a13cd348fc95fc059e8fa0e4b75b8ffcc7b61685a5fb
license    : MIT
component  : desktop
summary    : sway is an i3-compatible Wayland compositor
description: |
    sway is an i3-compatible Wayland compositor
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(cairo)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(json-c)
    - pkgconfig(libavcodec)
    - pkgconfig(libevdev)
    - pkgconfig(libcap)
    - pkgconfig(pango)
    - pkgconfig(wlroots)
rundeps    :
    - swaylock
setup      : |
    %meson_configure -Dgdk-pixbuf=enabled -Dxwayland=enabled
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 $pkgfiles/sway.desktop $installdir/usr/share/xsessions/sway.desktop
