name       : sway
version    : 0.12.2
release    : 5
source     :
    - https://github.com/SirCmpwn/sway/archive/0.12.2.tar.gz : 134387d4da1b912f31c0b23f75722d3896cd2560ef5a37775f75e7057cd4a010
license    : MIT
component  : desktop
summary    : sway is an i3-compatible Wayland compositor
description: |
    sway is an i3-compatible Wayland compositor
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(cairo)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(json-c)
    - pkgconfig(libavcodec)
    - pkgconfig(libcap)
    - pkgconfig(pango)
    - pkgconfig(wlc)
    - asciidoc
setup      : |
    %cmake -Dzsh-completions=ON .
build      : |
    %make
install    : |
    %make_install
